version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_arquivos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arquivos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_arquivos
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=arquivos_db
    volumes:
      - ./backend:/app
    working_dir: /app
    command: ["npm", "start"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend_arquivos
    restart: always
    ports:
      - "5173:5173"
    working_dir: /app
    command: ["npm", "run", "dev", "--", "--host"]

volumes:
  mysql_data:
