services:
  mysql:
    image: mysql:8.0
    container_name: mysql_arquivos
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: arquivos_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: backend_arquivos
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/app
    depends_on:
      - mysql

volumes:
  mysql_data:
